### ISSUE TITLE
1.1.0 crashes on long-press selection with Compose 1.12 due to incompatible clipboard implementation

### ISSUE THREAD

**Issue by eshan-gr** [MohamedRejeb/compose-rich-editor#799]
@MohamedRejeb 

Using richeditor-compose:1.1.0 with Jetpack Compose 1.12 causes a fatal exception when long-pressing inside BasicRichTextEditor.
Crash
FATAL EXCEPTION: main

java.lang.IllegalArgumentException:
Extracting native reference is only supported from
androidx.compose.ui.platform.AndroidClipboard instances
but received
com.mohamedrejeb.richeditor.clipboard.AndroidRichTextClipboardManager

    at androidx.compose.ui.platform.AndroidClipboard_androidKt.getNativeClipboardManager
    at androidx.compose.foundation.internal.ClipboardUtils.hasText
    at androidx.compose.foundation.text.selection.TextFieldSelectionManager_androidKt.hasAvailableTextToPaste
    at androidx.compose.foundation.text.selection.TextFieldSelectionManager.updateClipboardEntry$foundation
Environment
Kotlin: 2.4.10
Jetpack Compose: 1.12.0
RichEditor: 1.1.0
Android Gradle Plugin: 9.3.2

**Reproduction**
1.Add richeditor-compose:1.1.0.
2.Use BasicRichTextEditor.
3.Focus the editor and type some text.
4.Long-press the text to open the selection/context menu.
5.The application crashes before the menu is displayed.

Example:
BasicRichTextEditor(
    state = richTextState,
    modifier = Modifier.fillMaxWidth()
)

**Expected behavior**
The long-press selection menu should open normally, allowing copy, paste, and text selection.
Actual behavior
The application crashes while Compose checks whether text is available to paste.
Analysis
BasicRichTextEditor provides an AndroidRichTextClipboardManager through LocalClipboard.
However, newer Compose Foundation code expects the clipboard instance to implement 

androidx.compose.ui.platform.AndroidClipboard and attempts to extract the native clipboard manager from it.
The AndroidRichTextClipboardManager in version 1.1.0 delegates to Clipboard, but does not implement AndroidClipboard, causing the runtime exception.

**Workaround**
The following version contains an Android clipboard compatibility fix and works with Compose 1.12:
implementation(
    "com.mohamedrejeb.richeditor:richeditor-compose:1.0.0-cmp-1.12.0-beta03"
)

The corresponding implementation makes AndroidRichTextClipboardManager implement AndroidClipboard and exposes the underlying ClipboardManager.
Could you please restore or include this compatibility fix in a newer RichEditor release, or publish a 1.1.x artifact compatible with Compose 1.12?

**Comment by MohamedRejeb** [comment]
Hello
Thanks for reporting, please update to latest version `1.2` that's compatible with Compose `1.12`
